### ISSUE TITLE
max-width / max-height

### ISSUE THREAD

**Issue by thomasfw** [levymetal/jquery-resize-image-to-parent#5]
I've got max-width set to 100% on the image as a non-javascript fallback. This breaks the plugin (fix on line 21) ..
```javascript
// Reset max-height and max-width
obj.css({'max-height': 'none', 'max-width': 'none', 'width': '', 'height': '', 'margin-left': '', 'margin-top': ''});
```

**Comment by levymetal** [comment]
Thanks for the tip, but sorry - I'm not merging this into master. It's a matter of principle - I don't believe in adding complexity (no matter how small) to support an extremely small percentage of users. Especially those who are consciously making a decision to limit their experience on the web. 

Besides, if you want to offer *some* support for those users, setting `width: 100%` should work reasonably well and requires no extra code in the plugin. 

Alternatively, you can add styles that only apply when javascript is disabled. Check out Modernizr's source for `.no-js`, or this post: http://stackoverflow.com/a/4665769/551093
